export interface InventoryItemDTO {
  id: string;
  sku: string;
  barcode: string | null;
  name: string;
  brand: string | null;
  model: string | null;
  category: string | null;
  color: string | null;
  size: string | null;
  material: string | null;
  year: string | null;
  rarity: string | null;
  condition: string | null;
  conditionScore: number | null;
  conditionReason: string | null;
  aiConfidence: number | null;
  authenticityRisk: string | null;
  authenticityNotes: string | null;
  photos: string[];
  purchaseDate: string | null;
  purchasePrice: number | null;
  shippingCostEstimate: number | null;
  packagingCost: number | null;
  location: string | null;
  status: string;
  msrp: number | null;
  currentRetail: number | null;
  avgSoldPrice: number | null;
  lowestActive: number | null;
  highestSoldPrice: number | null;
  fastPrice: number | null;
  normalPrice: number | null;
  maxPrice: number | null;
  listingPrice: number | null;
  pricingStrategy: string;
  title: string | null;
  description: string | null;
  keywords: string[];
  itemSpecifics: Record<string, string>;
  marketplaces: string[];
  marketplaceStatus: Record<string, string>;
  marketplaceListings: Record<string, { listingId?: string; url?: string; error?: string }>;
  salePrice: number | null;
  platformFees: number | null;
  soldDate: string | null;
  daysListed: number | null;
  profit: number | null;
  roi: number | null;
  profitMargin: number | null;
  createdAt: string;
  updatedAt: string;
}
